(function(root){
'use strict';
const mod=(x,q=17)=>((x%q)+q)%q;
const power=(a,e,q=17)=>{let x=1;for(let i=0;i<e;i++)x=mod(x*a,q);return x;};
const dft=(a,w=4,q=17)=>a.map((_,k)=>mod(a.reduce((sum,x,i)=>sum+x*power(w,i*k,q),0),q));
const inverse=(a)=>dft(a,13).map(x=>mod(x*13));
const cyclic=(a,b)=>{const c=Array(a.length).fill(0);a.forEach((x,i)=>b.forEach((y,j)=>c[(i+j)%a.length]+=x*y));return c.map(x=>mod(x));};
const hw=x=>{let n=0;for(let i=0;i<16;i++)n+=(x>>>i)&1;return n;};
const fourProduct=(a,b)=>{const A=dft(a),B=dft(b),P=A.map((x,i)=>mod(x*B[i])),raw=dft(P,13),c=raw.map(x=>mod(x*13));return {A,B,P,raw,c,direct:cyclic(a,b)};};
const lessons=[
{id:'start',nav:'先认识四个格子',title:'一个多项式，两种记录方式',lead:'先不用记新名词。拖动一个系数，看看“格子里的数”和“代入之后的值”怎样一起变化。',tag:'从直觉开始'},
{id:'wrap',nav:'高次项为什么折回',title:'同一个 x⁵，为什么有时变号？',lead:'把乘法拆成“次数相加”和“按规则折回”两步。两种规则放在一起，差别就看得见。',tag:'循环与负循环 · q = 17'},
{id:'roots',nav:'单位根像怎样的循环',title:'乘同一个数，走一圈回到 1',lead:'每一步都乘 ω，再模 17。观察四个取值点是否重复，理解 NTT 为什么要挑特殊的点。',tag:'四次本原单位根 · q = 17'},
{id:'ntt4',nav:'四点 NTT 完整手算',title:'把“换表示后相乘”完整算一遍',lead:'先计算四个点值，再对应相乘，最后恢复系数。每个数字都能从上一行算出来。',tag:'4 点循环 NTT · 教学模型'},
{id:'butterfly',nav:'一个蝶形怎样工作',title:'两个数进入，两个数出来',lead:'让一条算式经过乘法、取模、加减与写回。跟着高亮位置走，不必一次理解整张变换网络。',tag:'基本运算单元 · q = 17'},
{id:'realntt',nav:'真实 256 系数 NTT',title:'把小例子接到真实 ML-KEM 参数',lead:'现在使用 q = 3329、n = 256。七层变换、128 个二系数块，以及逆变换都实际计算。',tag:'FIPS 203 算法 9–12 · 标准整数表示'},
{id:'register',nav:'算式落到寄存器',title:'结果相同，翻转的比特可以不同',lead:'把一个数写进 8 位寄存器。观察旧值、新值和翻转位置，再区分数学结果与硬件活动。',tag:'HW / HD 教学模型 · 非实测功耗'},
];
const maxSteps={wrap:3,roots:4,ntt4:8,butterfly:4,realntt:7,register:3};
function create(ctx){
const {M,$,state,player,table,note,details,status,slider,num,array,vec,poly,facts,stop,setStep,syncPlayer,sourceLinks}=ctx;
const s={start:{value:2,point:4},roots:{omega:4},four:{preset:'basic',a:[1,2,0,0],b:[3,1,0,0]},butterfly:{u:1,v:2,z:4},wrap:{i:3,j:2},real:{preset:'small',block:0,cache:null},register:{old:0,next:9}};
const presets={basic:{a:[1,2,0,0],b:[3,1,0,0]},dense:{a:[1,2,3,4],b:[4,1,0,2]},identity:{a:[1,2,3,4],b:[1,0,0,0]},wrap:{a:[0,0,0,1],b:[0,0,1,0]}};
const wrapLab=(content,controls='',withPlayer=true)=>`<section class="surface"><div class="controls">${controls}</div>${content}${withPlayer?player():''}</section>`;
const output=()=>'<div id="labOutput" aria-live="polite"></div>';
const aim=(remember,tryit)=>`<div class="lesson-prompts"><p><b>这一页记住</b>${remember}</p><p><b>动手试一下</b>${tryit}</p></div>`;
const question=(text,answer)=>details('先想一想：'+text,`<p>${answer}</p>`);
const select=(id,label,items,value)=>`<label for="${id}">${label}</label><select id="${id}">${items.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''} ${v==='custom'?'disabled':''}>${t}</option>`).join('')}</select>`;
const slots=(a,label='系数',active=-1)=>`<div class="slot-row">${a.map((x,i)=>`<div class="slot ${i===active?'selected':''}"><small>${label==='系数'?['常数项','x 的系数','x² 的系数','x³ 的系数'][i]:label+' '+i}</small><strong>${x}</strong></div>`).join('')}</div>`;
const bits=(x,width=8,mask=0)=>`<div class="register-bits" style="--bitcount:${width}">${Array.from({length:width},(_,i)=>{const bit=width-1-i,v=(x>>>bit)&1;return `<span class="register-bit ${v?'one':''} ${(mask>>>bit)&1?'flipped':''}"><small>b${bit}</small>${v}</span>`;}).join('')}</div>`;
const bodies={
start:()=>wrapLab(`<div class="grid-lab"><div>${slider('x-start-value','x 的系数',s.start.value,0,16)}${slider('x-start-point','代入的位置 r',s.start.point,0,16)}<p class="hint">系数告诉我们“每种次数有多少”；点值告诉我们“把 x 换成 r 后得到多少”。</p></div>${output()}</div>`,'',false)+aim('系数和点值是不同的数字，但可以描述同一个多项式。','把 x 的系数从 2 改为 3，再把 r 从 4 改为 1。')+`<div class="path-grid"><a href="#overview"><b>路径一 · 建立直觉</b><span>握手 → 模运算 → 带噪声手算</span><small>先理解双方为什么能得到同一秘密</small></a><a href="#roots"><b>路径二 · 算懂 NTT</b><span>单位根 → 四点手算 → 蝶形</span><small>再理解换一种表示为什么有帮助</small></a><a href="#realntt"><b>路径三 · 走进实现</b><span>真实 NTT → 完整 KEM → 寄存器</span><small>最后把数学节点接到硬件节点</small></a></div>`+question('只知道一个点值，能确定四个系数吗？','一般不能。四个系数需要足够的独立信息。四点循环 NTT 选取四个不同且满足特定规律的点，使次数小于 4 的多项式可以被唯一恢复。它不压缩信息，也不隐藏秘密。')+`<p class="sources">配套阅读：<a href="./TEACHING_GUIDE.zh-CN.md">逐页讲解与练习答案</a> · <a href="../../docs/09-ntt.md">仓库 NTT 与泄漏章节</a></p>`,
roots:()=>wrapLab(output(),select('x-root','每一步乘',[['4','ω = 4 · 正确四阶根'],['13','ω = 13 · 另一四阶根'],['1','ω = 1 · 每次停在原处'],['16','ω = 16 · 两步就返回']],s.roots.omega))+aim('四次本原单位根要恰好走四步回到 1，前四个点不能重复。','切换到 ω = 16：它满足 ω⁴ = 1，但为什么仍不能做四点可逆变换？')+question('时钟上的圆弧代表什么？','只是把模 17 的 17 个剩余数排成一圈，方便追踪乘法落点；它不是复平面里的单位圆，也不代表每次等角度旋转。')+note('ω = 16 的问题','前四个点只有 [1,16,1,16]，信息重复；ω = 4 的前四个点为 [1,4,16,13]，信息独立。只检查 ω⁴ = 1 不够，还要排除更早返回。'),
ntt4:()=>wrapLab(`<div class="grid2 below">${['a','b'].map(k=>`<div><h3>${k}(x) 的系数</h3><div class="coef-entry">${s.four[k].map((v,i)=>`<label for="x-four-${k}-${i}">${['常数','x','x²','x³'][i]}<input type="number" id="x-four-${k}-${i}" min="-16" max="16" step="1" value="${v}"></label>`).join('')}</div></div>`).join('')}</div>${output()}`,select('x-four-preset','算例',[['custom','自定义输入'],['basic','对话里的例子：(1+2x)(3+x)'],['dense','四个系数都参与'],['identity','乘以 1：结果不变'],['wrap','x³ × x²：发生循环折回']],s.four.preset))+aim('完整 NTT 把卷积变成点值相乘；逆变换把结果带回系数。','先跑默认例子，再选 x³ × x²。观察为什么最后是 x，而不是 x⁵。')+note('本页使用 x⁴ − 1','四点循环 NTT 算的是模 x⁴ − 1 的乘法，x⁴ = +1。默认例子最高次数为 2，没有折回；真实 ML-KEM 的规则为 x²⁵⁶ = −1，见“真实 256 系数 NTT”。',true)+question('为什么求值后每个位置可以独立相乘？','因为对任意取值点 r，都有 (a·b)(r)=a(r)b(r)。特殊单位根进一步使求值和恢复可以用蝶形快速完成。直接逐点代入的教学算法本身仍是平方级工作量。'),
butterfly:()=>wrapLab(`<div class="form-grid">${num('x-bf-u','输入 u',s.butterfly.u,0,16)}${num('x-bf-v','输入 v',s.butterfly.v,0,16)}${num('x-bf-z','因子 ζ',s.butterfly.z,1,16)}</div>${output()}`)+aim('一个常见蝶形完成一次模乘，以及一加一减。','保持 u=1、ζ=4，把 v 从 2 改成 3，先预测两个输出。')+question('为什么叫蝶形？','两个输入分别影响两个输出，数据连线展开后形似蝴蝶。名称描述连接方式；是否先乘后加、输入输出顺序如何排列，要以所用变换算法为准。')+note('从蝶形到整张网络','四点变换有两层，每层两个蝶形；后面的“八点 NTT”实验有三层，每层四个蝶形。规律是把大问题分成更小的、可以复用结果的问题。'),
wrap:()=>wrapLab(`<div class="form-grid">${num('x-wrap-i','a 的次数 i',s.wrap.i,0,3)}${num('x-wrap-j','b 的次数 j',s.wrap.j,0,3)}</div>${output()}`)+aim('模数 q 决定系数如何取余；xⁿ ± 1 决定次数如何折回。这是两条不同规则。','先试 x³×x²，再试 x×x。第二个例子不折回，两种规则结果相同。')+question('−1 和 16 是两个不同的系数吗？','在模 17 的数学运算里，它们表示同一个剩余类。显示为 −1 便于看懂符号，显示为 16 便于规范化存储；硬件中的具体位模式还取决于位宽和编码。'),
realntt:()=>wrapLab(`<div class="real-controls">${slider('x-real-block','查看二系数块编号',s.real.block,0,127)}</div>${output()}`,select('x-real-preset','实际输入',[['small','1+2x 与 3+x'],['wrap','x²⁵⁵ 与 x²：负循环折回'],['dense','256 个小系数全部参与']],s.real.preset))+aim('ML-KEM 的末端是 128 个二系数块，不是 256 个标量点值。','选择 x²⁵⁵×x²，检查逆变换所得系数：为什么 x 项是 3328？')+note('这个实验计算到什么程度？','这里独立运行 FIPS 203 算法 9–12 的数学运算，并与直接负循环卷积核对。使用规范化整数表示；不展示 Montgomery 编码、延迟约减或真实芯片时序。')+question('为什么逆变换最后乘 3303？','标准的七层不完全 NTT 需要乘 128 的模逆元：128×3303 ≡ 1（mod 3329）。不能直接套用完整 256 点变换的归一化系数。')+sourceLinks(),
register:()=>wrapLab(`<div class="form-grid">${num('x-reg-old','寄存器旧值',s.register.old,0,255)}${num('x-reg-next','待写入新值',s.register.next,0,255)}</div><div class="controls"><button data-act="x-reg-preset" data-old="0">0 → 9</button><button data-act="x-reg-preset" data-old="8">8 → 9</button><button data-act="x-reg-preset" data-old="9">9 → 9</button></div>${output()}`)+aim('HW 数新值里有多少个 1；HD 数旧值到新值有多少位翻转。','依次点三个预设。写入结果都为 9，为什么翻转数依次是 2、1、0？')+`<section class="surface below"><h2>同一模数值，也可能使用不同位模式</h2>${table(['数学表示','一种具体存储方式','二进制位模式','HW'],[['9','12 位无符号','0000 0000 1001',2],['−3320 ≡ 9 (mod 3329)','16 位二进制补码',(65536-3320).toString(2).padStart(16,'0').match(/.{4}/g).join(' '),hw(65536-3320)]])}<p class="hint">这些存储方式仅用于对照。实际实现必须确定字长、编码、Montgomery 域与约减策略，再建立预测。</p></section>`+note('翻转数量不等于测得的瓦数','本页只计算理想 HW / HD。实际功耗、电磁还受电容、毛刺、时钟、布局布线和测量链影响；没有测量数据，就不能把条形高度解释成真实波形或攻击成功率。',true)+`<p class="sources"><a href="../../docs/02-physical-leakage.md">继续读：CMOS、寄存器与泄漏模型</a> · <a href="../../docs/07-masking.md">继续读：掩码与硬件毛刺</a></p>`,
};
function drawStart(){const a=[1,s.start.value,0,0],r=s.start.point,raw=1+s.start.value*r;$('labOutput').innerHTML=`<div class="formula large">a(x) = ${poly(a)}</div>${slots(a,'系数',1)}<div class="evaluation-card"><span>把 x 换成 ${r}</span><div class="formula">a(${r}) = 1 + ${s.start.value} × ${r}<br>= ${raw} ≡ <strong>${mod(raw)}</strong> (mod 17)</div></div><p class="hint">只改一个格子，多个取值点的结果都可能改变。</p>`;}
function drawRoots(){const w=s.roots.omega,n=state.steps.roots,values=Array.from({length:5},(_,i)=>power(w,i)),x=values[n],points=Array.from({length:17},(_,i)=>({x:190+135*Math.sin(i*Math.PI*2/17),y:180-135*Math.cos(i*Math.PI*2/17)}));let svg=`<svg viewBox="0 0 380 370" class="root-clock" role="img" aria-label="模17乘法落点，当前${x}"><circle cx="190" cy="180" r="135" fill="none" stroke="#dce4e9"/>`;for(let i=1;i<=n;i++){const a=points[values[i-1]],b=points[values[i]];svg+=`<path d="M${a.x},${a.y} Q190,180 ${b.x},${b.y}" fill="none" stroke="#247e91" opacity="${i===n?1:.24}" stroke-width="${i===n?3:1}"/>`;}points.forEach((p,i)=>{svg+=`<circle cx="${p.x}" cy="${p.y}" r="${i===x?19:14}" fill="${i===x?'#087f78':'#eef3f7'}"/><text x="${p.x}" y="${p.y+5}" text-anchor="middle" font-size="14" fill="${i===x?'white':'#4b6070'}">${i}</text>`;});svg+=`<text x="190" y="176" text-anchor="middle" font-size="17" fill="#182c36">每一步 × ${w}</text><text x="190" y="203" text-anchor="middle" font-size="14" fill="#596a75">再模 17</text></svg>`;const unique=new Set(values.slice(0,4)).size,ok=unique===4&&values[4]===1;$('labOutput').innerHTML=`<div class="grid-lab"><div>${svg}</div><div class="step-copy"><div class="kicker">从 ω⁰ = 1 出发 · 第 ${n} 步</div><h2>${n===0?'先站在 1 上':`${values[n-1]} × ${w} ≡ ${x}`}</h2><div class="power-strip">${values.map((v,i)=>`<span class="${i===n?'active':''} ${i>n?'future':''}"><small>ω<sup>${i}</sup></small>${i<=n?v:'?'}</span>`).join('')}</div><p>前四个取值点：<b class="mono">${vec(values.slice(0,4))}</b></p>${status(ok,'四个点互不重复，第 4 步回到 1','取值点提前重复，不能作为四点可逆 NTT 的根')}<p class="hint">第五个显示值是回到起点，用于确认循环长度；NTT 只取前四个点。</p></div></div>`;}
function drawFour(){const {a,b}=s.four,d=fourProduct(a,b),n=state.steps.ntt4,roots=[1,4,16,13],titles=['先记录输入系数','第一个点：r = 1','第二个点：r = 4','第三个点：r = 16','第四个点：r = 13','对应位置相乘','按逆根做变换','乘归一化因子 13','恢复系数，并核对'];let body='';
if(n===0)body=`<div class="grid2"><div class="formula">a(x) = ${poly(a)}</div><div class="formula">b(x) = ${poly(b)}</div></div><p>先预测乘积，再按“下一步”。本例使用四个取值点 1、4、16、13。</p>`;
if(n>=1&&n<=4){const k=n-1,weights=roots.map((_,i)=>power(roots[k],i));body=`<div class="formula-box formula">r = ${roots[k]}，权重 [1,r,r²,r³] = ${vec(weights)}</div>${['a','b'].map((name,j)=>{const coeff=j?b:a,terms=coeff.map((x,i)=>x*weights[i]);return `<div class="equation-ribbon"><b>${name}(${roots[k]})</b><span class="mono">${coeff.map((x,i)=>`(${x})×${weights[i]}`).join(' + ')}<br>= ${terms.join(' + ')} = ${terms.reduce((x,y)=>x+y,0)} ≡ <strong>${j?d.B[k]:d.A[k]}</strong></span></div>`;}).join('')}`;}
if(n===5)body=`<p>每个位置只与同一个位置相乘。此处的四个数都是点值。</p><div class="formula-box formula">P[k] = Â[k] × B̂[k] mod 17</div>`;
if(n===6)body=`<p>逆根是 13，因为 4×13 ≡ 1。先按这个逆根做一次变换：</p>${table(['位置 j','逆变换权重','加权求和再模 17'],d.raw.map((x,j)=>[j,vec(Array.from({length:4},(_,k)=>power(13,j*k))),x]))}<p class="hint">还没结束！这一行还需要统一乘 4⁻¹，才能恢复系数。</p>`;
if(n===7)body=`<div class="formula-box formula">4⁻¹ = 13，因为 4×13 ≡ 1 (mod 17)</div>${table(['位置','未归一化值','乘 13，再模 17'],d.raw.map((x,i)=>[i,x,`${x} × 13 = ${x*13} ≡ ${d.c[i]}`]))}`;
if(n===8)body=`<p>逆变换恢复的是下列系数：</p>${slots(d.c)}<div class="formula-box formula">c(x) = ${poly(d.c)}</div>${status(d.c.every((x,i)=>x===d.direct[i]),'与直接循环卷积逐系数相同','计算不一致')}<p class="mono">直接循环卷积结果：${vec(d.direct)}</p>`;
$('labOutput').innerHTML=`<div class="step-copy"><div class="kicker">步骤 ${n+1} / 9</div><h2>${titles[n]}</h2></div>${body}${n>=1&&n<=5?table(['k','r = ωᵏ','a 的点值','b 的点值','相乘并模 17'],roots.map((r,k)=>[k,r,n>k?d.A[k]:'待计算',n>k?d.B[k]:'待计算',n>=5?d.P[k]:'待计算'])):''}`;}
function drawButterfly(){const p=s.butterfly,n=state.steps.butterfly,raw=p.z*p.v,t=mod(raw),sum=p.u+t,diff=p.u-t,left=mod(sum),right=mod(diff);const node=(x,y,w,label,val,live)=>`<g class="${live?'node-live':''}"><rect x="${x}" y="${y}" width="${w}" height="66" rx="9" fill="${live?'#e2f5ef':'#f0f4f7'}" stroke="${live?'#087f78':'#dce4e9'}"/><text x="${x+w/2}" y="${y+24}" text-anchor="middle" font-size="14" fill="#526976">${label}</text><text x="${x+w/2}" y="${y+49}" text-anchor="middle" font-size="20" fill="#12313c">${val}</text></g>`;let svg=`<svg class="butterfly-svg" viewBox="0 0 760 260" role="img" aria-label="蝶形数据通路，u=${p.u},v=${p.v},旋转因子${p.z}"><g fill="none" stroke="#87aab5" stroke-width="2"><path d="M130 55H450V66H560"/><path d="M130 55H175V205H560"/><path d="M130 205H215"/><path d="M390 205H450V99H560"/><path d="M390 205H560"/></g>${node(10,20,120,'输入 u',p.u,n===0)}${node(10,172,120,'输入 v',p.v,n===0)}${node(215,172,175,`乘 ζ=${p.z}，模 17`,n>=2?t:n===1?raw:'待计算',n===1||n===2)}${node(560,35,175,'u + t，模 17',n>=4?left:n===3?sum:'待计算',n>=3)}${node(560,172,175,'u − t，模 17',n>=4?right:n===3?diff:'待计算',n>=3)}</svg>`;const rows=[['读入两个数',`u=${p.u}，v=${p.v}，ζ=${p.z}`],['先做整数乘法',`ζv=${p.z}×${p.v}=${raw}`],['把乘积取模',`${raw} mod 17=${t}`],['分别加一次、减一次',`${p.u}+${t}=${sum}；${p.u}−${t}=${diff}`],['输出规范化的两个余数',`${sum} mod 17=${left}；${diff} mod 17=${right}`]];$('labOutput').innerHTML=`<div class="step-copy"><div class="kicker">操作 ${n+1} / 5</div><h2>${rows[n][0]}</h2></div>${svg}<div class="formula-box formula">${rows[n][1]}</div>${n===4?`<p>输入 [${p.u},${p.v}] → 输出 [${left},${right}]。旋转因子 ζ 由所在层和位置决定。</p>`:''}`;}
function drawWrap(){const {i,j}=s.wrap,n=state.steps.wrap,deg=i+j,fold=deg>=4,index=deg%4,pos=Array(4).fill(0),neg=Array(4).fill(0);pos[index]=1;neg[index]=fold?16:1;$('labOutput').innerHTML=`<div class="step-copy"><div class="kicker">步骤 ${n+1} / 4</div><h2>${['先看两个单项式','相乘时，次数相加','分别按两条规则折回','系数取模，比较结果'][n]}</h2></div><div class="formula-box formula">x<sup>${i}</sup> × x<sup>${j}</sup> ${n>=1?'= x<sup>'+deg+'</sup>':''}</div><div class="rule-grid"><article><span class="tag">循环：x⁴ − 1</span><h3>x⁴ = +1</h3><div class="formula">${n>=2?`x<sup>${deg}</sup> = +x<sup>${index}</sup>`:'等待折回'}</div>${n>=3?slots(pos):''}</article><article><span class="tag toy">负循环：x⁴ + 1</span><h3>x⁴ = −1</h3><div class="formula">${n>=2?`x<sup>${deg}</sup> = ${fold?'−':'+'}x<sup>${index}</sup>`:'等待折回'}</div>${n>=3?slots(neg):''}</article></div><p class="hint">${fold?'次数达到 4：折回时两种规则的符号不同。':'次数小于 4：没有发生折回，两种规则结果相同。'}${n>=3&&fold?' −1 在模 17 下显示为 16。':''}</p>`;}
function realData(){if(s.real.cache)return s.real.cache;const a=Array(256).fill(0),b=Array(256).fill(0);if(s.real.preset==='small'){a[0]=1;a[1]=2;b[0]=3;b[1]=1;}else if(s.real.preset==='wrap'){a[255]=1;b[2]=1;}else for(let i=0;i<256;i++){a[i]=i%5-2;b[i]=(i*3+1)%7-3;}const R=root.RealNTT,A=R.forward(a),B=R.forward(b),c=R.multiply(a,b),direct=R.schoolbook(a,b),nonzero=c.map((x,i)=>({i,x})).filter(x=>x.x);s.real.cache={a,b,A,B,c,direct,nonzero};return s.real.cache;}
function drawRealNTT(){const d=realData(),n=state.steps.realntt,k=s.real.block,start=Math.floor((k*2)/16)*16,stage=n?d.A.stages[n-1]:d.A.input,ga=root.RealNTT.gamma(k),ap=d.A.output.slice(2*k,2*k+2),bp=d.B.output.slice(2*k,2*k+2),cp=root.RealNTT.baseMultiply(ap,bp,ga);const rows=Array.from({length:16},(_,j)=>{const i=start+j;return [i,d.A.input[i],...d.A.stages.map((a,t)=>t<n?a[i]:'·')];});let description=s.real.preset==='small'?'a=1+2x，b=3+x':s.real.preset==='wrap'?'a=x²⁵⁵，b=x²':'aᵢ=(i mod 5)−2，bᵢ=((3i+1) mod 7)−3';$('labOutput').innerHTML=`<div class="step-copy"><div class="kicker">${n===0?'原始系数':`第 ${n} / 7 层完成`}</div><h2>${n===0?'先看输入，再执行七层变换':`配对距离 len = ${128/2**(n-1)}`}</h2><p>${description}；表格显示 a 的 16 个连续位置。</p></div>${table(['位置','输入','层 1','层 2','层 3','层 4','层 5','层 6','层 7'],rows,'real-stage-table')}<p class="hint">当前窗口：${start}～${start+15}。拖动块编号可查看其他位置；“·”代表该层尚未执行。每层 128 个蝶形，共 896 个。</p>${details('用颜色浏览当前全部 256 个数',`<div class="coefficient-map">${stage.map((x,i)=>`<span title="位置 ${i}：${x}" style="background:hsl(174 45% ${94-x/3329*42}%)">${i}</span>`).join('')}</div><p class="hint">颜色只编码当前余数大小；序号仍是数组位置，不是秘密强度。</p>`)}<section class="block-product"><h3>完整变换后的第 ${k} 个二系数块</h3><p class="hint">下面单独展示已完成全部七层时的块乘法，用于把变换接回多项式乘法。</p><div class="formula-box formula">γ = ${ga}<br>A 块 = ${vec(ap)}，B 块 = ${vec(bp)}<br>c₀ = ${ap[0]}×${bp[0]} + ${ga}×${ap[1]}×${bp[1]} ≡ ${cp[0]}<br>c₁ = ${ap[0]}×${bp[1]} + ${ap[1]}×${bp[0]} ≡ ${cp[1]} (mod 3329)</div><p>全部 128 个块相乘，再逆变换，得到：</p><div class="formula">${s.real.preset==='small'?'3 + 7x + 2x²':s.real.preset==='wrap'?'3328x ≡ −x (mod 3329)':`共 ${d.nonzero.length} 个非零系数`}</div>${status(d.c.every((x,i)=>x===d.direct[i]),'全部 256 个系数与直接负循环卷积一致','乘法结果不一致')}${details('展开全部输入和最终系数',table(['位置 i','输入 aᵢ（规范化）','输入 bᵢ（规范化）','逆变换结果 cᵢ','直接卷积'],d.c.map((x,i)=>[i,mod(d.a[i],3329),mod(d.b[i],3329),x,d.direct[i]])))}</section>`;}
function drawRegister(){const p=s.register,n=state.steps.register,mask=p.old^p.next,weight=hw(p.next),distance=hw(mask);$('labOutput').innerHTML=`<div class="step-copy"><div class="kicker">步骤 ${n+1} / 4</div><h2>${['寄存器里原来存着什么','准备好下一次要写入的值','比较哪些位需要翻转','写入完成，解释两个计数'][n]}</h2></div><div class="register-panel"><label>旧值 ${p.old}</label>${bits(p.old)}${n>=1?`<label>新值 ${p.next}</label>${bits(p.next,8,n>=2?mask:0)}`:''}${n>=2?`<label>异或 XOR：1 表示这一位发生翻转</label>${bits(mask,8,mask)}<p class="hint">橙色边框标出翻转位。</p>`:''}</div>${n>=3?`<div class="model-bars"><div><span>HW(新值)</span><i style="--size:${weight/8*100}%"></i><b>${weight}</b></div><div><span>HD(旧值,新值)</span><i style="--size:${distance/8*100}%"></i><b>${distance}</b></div></div><p>新值有 ${weight} 个 1；本次写入有 ${distance} 位改变。这两种计数描述不同的物理模型。</p>`:''}`;}
const draws={start:drawStart,roots:drawRoots,ntt4:drawFour,butterfly:drawButterfly,wrap:drawWrap,realntt:drawRealNTT,register:drawRegister};
function reset(id){stop();if(id in maxSteps)state.steps[id]=0;draws[id]();syncPlayer();}
function clearInvalid(id){const el=$(id);if(el){el.setCustomValidity('');el.removeAttribute('aria-invalid');}}
return {has:id=>!!bodies[id],body:id=>bodies[id](),draw:id=>draws[id](),
click(act,b){if(act==='x-reg-preset'){s.register={old:+b.dataset.old,next:9};$('x-reg-old').value=s.register.old;$('x-reg-next').value=9;clearInvalid('x-reg-old');clearInvalid('x-reg-next');reset('register');return true;}return false;},
input(id,v,el){if(id==='x-start-value'||id==='x-start-point'){s.start[id==='x-start-value'?'value':'point']=+el.value;$(id+'Val').value=el.value;drawStart();}
if(/^x-four-[ab]-[0-3]$/.test(id)){const parts=id.split('-');s.four[parts[2]][+parts[3]]=v;s.four.preset='custom';$('x-four-preset').value='custom';reset('ntt4');}
if(id.startsWith('x-bf-')){s.butterfly[id.slice(5)]=v;reset('butterfly');}
if(id==='x-wrap-i'||id==='x-wrap-j'){s.wrap[id.slice(-1)]=v;reset('wrap');}
if(id==='x-real-block'){s.real.block=+el.value;$(id+'Val').value=el.value;stop();drawRealNTT();}
if(id==='x-reg-old'||id==='x-reg-next'){s.register[id==='x-reg-old'?'old':'next']=v;reset('register');}},
change(id,v){if(id==='x-root'){s.roots.omega=+v;reset('roots');}
if(id==='x-four-preset'){if(v==='custom')return;const p=presets[v];s.four={preset:v,a:[...p.a],b:[...p.b]};for(const name of ['a','b'])s.four[name].forEach((x,i)=>{$(`x-four-${name}-${i}`).value=x;clearInvalid(`x-four-${name}-${i}`);});reset('ntt4');}
if(id==='x-real-preset'){s.real.preset=v;s.real.cache=null;reset('realntt');}}
};
}
const api={lessons,maxSteps,create,math:{mod,power,dft,inverse,cyclic,hw,fourProduct}};root.CourseExtra=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
